spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    password: Mrovo@986
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE


#Eureka Config

#eureka.client.serviceUrl.defaultZone: http://localhost:8761/
#eureka.client.register-with-eureka: true
#eureka.client.fetch-registry: true
#eureka.instance.prefer-Ip-Address: true
#eureka.instance.preferIpAddress: true

server:
  port: 8082