spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user_service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**


server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





